<?php
/**
 * Builder shortcode icon list
 *
 * @package flatsome
 */

return array(
	''                     => 'None',
	'icon-500px'           => '500px',
	'icon-angle-down'      => 'Arrow Down',
	'icon-angle-left'      => 'Arrow Left',
	'icon-angle-right'     => 'Arrow Right',
	'icon-angle-up'        => 'Arrow Up',
	'icon-certificate'     => 'Certificate',
	'icon-chat'            => 'Chat',
	'icon-checkmark'       => 'Checkmark',
	'icon-clock'           => 'Clock',
	'icon-cross'           => 'Cross',
	'icon-discord'         => 'Discord',
	'icon-dribbble'        => 'Dribbble',
	'icon-envelop'         => 'Envelope',
	'icon-expand'          => 'Expand',
	'icon-facebook'        => 'Facebook',
	'icon-feed'            => 'Feed',
	'icon-flickr'          => 'Flickr',
	'icon-gift'            => 'Gift',
	'icon-google-plus'     => 'Google Plus',
	'icon-heart'           => 'Heart',
	'icon-heart-o'         => 'Heart Outline',
	'icon-instagram'       => 'Instagram',
	'icon-linkedin'        => 'linkedIn',
	'icon-lock'            => 'Lock',
	'icon-map-pin-fill'    => 'Map Pin',
	'icon-menu'            => 'Menu',
	'icon-pen-alt-fill'    => 'Pen',
	'icon-phone'           => 'Phone',
	'icon-pinterest'       => 'Pinterest',
	'icon-play'            => 'Play',
	'icon-plus'            => 'Plus',
	'icon-search'          => 'Search',
	'icon-shopping-bag'    => 'Shopping Bag',
	'icon-shopping-basket' => 'Shopping Basket',
	'icon-shopping-cart'   => 'Shopping Cart',
	'icon-skype'           => 'Skype',
	'icon-snapchat'        => 'SnapChat',
	'icon-star'            => 'Star',
	'icon-star-o'          => 'Star Outline',
	'icon-tag'             => 'Tag',
	'icon-telegram'        => 'Telegram',
	'icon-threads'         => 'Threads',
	'icon-tiktok'          => 'TikTok',
	'icon-tumblr'          => 'Tumblr',
	'icon-twitch'          => 'Twitch',
	'icon-twitter'         => 'Twitter',
	'icon-user'            => 'User',
	'icon-user-o'          => 'User Outline',
	'icon-vk'              => 'VKontakte',
	'icon-whatsapp'        => 'WhatsApp',
	'icon-x'               => 'X (social media)',
	'icon-youtube'         => 'Youtube',
);
