<?php
return ['domain'=>'flatsome','plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'fa_IR','project-id-version'=>'l10n-flatsome','pot-creation-date'=>'2024-12-16T13:56:13+00:00','po-revision-date'=>'2024-12-16 14:00','x-generator'=>'WP-CLI 2.10.0','messages'=>['Oops! That page can&rsquo;t be found.'=>'با عرض پوزش.
صفحه مورد نظر شما پیدا نشد','It looks like nothing was found at this location. Maybe try one of the links below or a search?'=>'به نظر میرسد آدرسی که وارد کرده اید اشتباه است. میتوانید از لینک های زیر و یا قسمت جست و جو استفاده کنید','Comment navigation'=>'تنظیمات دیدگاه ها','Comments are closed.'=>'ارسال دیدگاه بسته شده است.','Published <span class="entry-date"><time class="entry-date" datetime="%1$s">%2$s</time></span> at <a href="%3$s" title="Link to full-size image">%4$s &times; %5$s</a> in <a href="%6$s" title="Return to %7$s" rel="gallery">%8$s</a>'=>'منتشر شده در <span class="entry-date"><time class="entry-date" datetime="%1$s">%2$s</time></span> at <a href="%3$s" title="Link to full-size image">%4$s &times; %5$s</a> in <a href="%6$s" title="Return to %7$s" rel="gallery">%8$s</a>
','Edit'=>'ویرایش','<a class="comment-link" href="#respond" title="Post a comment">Post a comment</a> or leave a trackback: <a class="trackback-link" href="%s" title="Trackback URL for your post" rel="trackback">Trackback URL</a>.'=>'<a class="comment-link" href="#respond" title="دیدگاه ارسال کنید">دیدگاه ارسال کنید</a> یا بازتاب بفرستید <a class="trackback-link" href="%s" title="لینک بازتاب نوشته شما" rel="trackback">Trackback URL</a>.
','Comments are closed, but you can leave a trackback: <a class="trackback-link" href="%s" title="Trackback URL for your post" rel="trackback">Trackback URL</a>.'=>'ارسال کامت بسته شده است ولی شما میتوانید بازتاب ارسال کنید <a class="trackback-link" href="%s" title="لینک ارسال بازتاب برای پست شما" rel="trackback">Trackback URL</a>.
','Trackbacks are closed, but you can <a class="comment-link" href="#respond" title="Post a comment">post a comment</a>.'=>'ارسال بازتاب بسته شده است ولی می توانید <a class="comment-link" href="#respond" title="دیدگاه ارسال کنید">دیدگاه ارسال کنید</a>.
','Both comments and trackbacks are currently closed.'=>'ارسال دیدگاه و بازتاب بشته شده است','<span class="meta-nav">&larr;</span> Previous'=>'<span class="meta-nav">&larr;</span> قبلی','Next <span class="meta-nav">&rarr;</span>'=>'بعدی <span class="meta-nav">&rarr;</span>
','Cancel'=>'لغو','Name'=>'نام','Version'=>'ورژن','Register'=>'ثبت نام','Status'=>'وضعیت','Quick View'=>'مشاهده','New'=>'جدید','Hot'=>'جدید','Sale'=>'حراج','Popular'=>'محبوب','Main Menu'=>'منو اصلی','Main Menu - Mobile'=>'منو اصلی - موبایل','Footer Menu'=>'منو فوتر','My Account Menu'=>'منو اکانت','Sidebar'=>'سایدبار','Footer 1'=>'فوتر 1','Footer 2'=>'فوتر 2','Send us an email'=>'برای ما ایمیل بفرستید','Subscribe to RSS'=>'اشتراک در RSS','Flickr'=>'Flickr
','Follow on VKontakte'=>'دنبال در VKontakte دنبال کنید','Share on WhatsApp'=>'اشتراک گذاری در WhatsApp','Share on Facebook'=>'اشتراک گذاری در Facebook','Share on Twitter'=>'اشتراک گذاری در Twitter','Email to a Friend'=>'ایمیل به دوستان','Pin on Pinterest'=>'پین(pin) در Pinterest','Share on VKontakte'=>'اشتراک گذاری در TVKontakte','Share on Tumblr'=>'اشتراک گذاری در Tumblr','<span class="icon-angle-left"></span> Older posts'=>'<span class="icon-angle-left"></span> نوشته های قدیمی
','Newer posts <span class="icon-angle-right"></span>'=>'نوشته های جدیدتر <span class="icon-angle-right"></span>','Pingback:'=>'اشتراک ها:','%s <span class="says">says:</span>'=>'%s <span class="says">میگوید:</span>
','Your comment is awaiting moderation.'=>'دیدگاه شما در انتظار تایید است.','1: date, 2: time%1$s at %2$s'=>'%1$s در %2$s
','Flatsome Recent Posts'=>'Flatsome Recent Posts
','Recent Posts'=>'Recent Posts
','<strong>1</strong> Comment'=>'یک دیدگاه','<strong>%</strong> Comments'=>'% دیدگاه','Complete the look'=>'Complete the look
','Top Content'=>'بالای صفحه','Enter a value for this field. Shortcodes are allowed. This will be displayed at top of the category.'=>'یک مقدار برای این فیلد وارد کنید. shortcode مجاز است. این در بالای صفحه نمایش داده می شود.','Bottom Content'=>'پایین صفحه','Enter a value for this field. Shortcodes are allowed. This will be displayed at bottom of the category.'=>'یک مقدار برای این فیلد وارد کنید. shortcode مجاز است. این در پایین صفحه نمایش داده می شود.','Shop Sidebar'=>'سایدبار فروشگاه','Product Sidebar'=>'سایدبار صفحه محصول','Enable a custom bubble on this product.'=>'فعالسازی Bubble سفارشی برای این محصول','Custom Tab Content'=>'محتوای تب سفارشی','Enter content for custom product tab here. Shortcodes are allowed'=>'محتوای تب محصول سفارشی را اینجا وارد کنید. shortcode  مجاز است','Product Video'=>'ویدیو محصول','Enter a Youtube or Vimeo Url of the product video here. We recommend uploading your video to Youtube.'=>'لینک آدرس Youtube یا Vimdeo این محصول .ما توصیه می کنیم ویدیو را در Youtube آپلود کنید','Video'=>'ویدیو','Zoom'=>'زوم','Submit'=>'ارسال','Categories'=>'دسته بندی ها','Nothing Found'=>'نتیجه ای پیدا نشد','Ready to publish your first post? <a href="%1$s">Get started here</a>.'=>'آماده انتشار اولین نوشته خود هستید؟ <a href="%1$s">پس آغاز کنید</a>.
','Sorry, but nothing matched your search terms. Please try again with some different keywords.'=>'با عرض پوزش نتیجه ای برای جست و جوی شما پیدا نشد. 
می توانید از کلمات دیگر برای جست و جو استفاده کنید.','It seems we can&rsquo;t find what you&rsquo;re looking for. Perhaps searching can help.'=>'به نظر میرسد نمیتوانیم چیزی که می گردید پیدا کنیم &rsquo;t | &rsquo;re . لطفا از قسمت جست و جو استفاده کنید.
',', '=>', 
','This entry was posted in %1$s and tagged %2$s.'=>'دسته بندی: %1$s

برچسب ها: %2$s','This entry was posted in %1$s. Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.'=>'دسته بندی: %1$s

برچسب ها: %2$s','Continue reading <span class="meta-nav">&rarr;</span>'=>'ادامه <span class="meta-nav">&rarr;</span>
','Category Archives: %s'=>'آرشیو دسته بندی: %s','Tag Archives: %s'=>'آرشیو برچسب های: %s','Search Results for: %s'=>'نتایج جست و جوی : %s','Author Archives: %s'=>'آرشیو نویسنده: %s','Daily Archives: %s'=>'آرشیو روزانه: %s','Monthly Archives: %s'=>'آرشیو ماهانه: %s','Yearly Archives: %s'=>'آرشیو سالانه: %s','Asides'=>'کلمات قصار','Images'=>'عکس ها','Videos'=>'ویدیو ها','Quotes'=>'نقل قول','Links'=>'لینک ها','Posted in %1$s'=>'ارسال شده در : %1$s','Tagged %1$s'=>'برچسب: %1$s','Leave a comment'=>'ارسال دیدگاه','Shopping Cart'=>'سبد خرید','Checkout details'=>'جزئیات پرداخت','Order Complete'=>'اتمام عملیات خرید']];